---
- name: create service for deployment
  hosts: kubernetes
#  become: true
#  user: root

  tasks:
  - name: cp valaxy-service
    copy: 
      src: /opt/k8s-lab/valaxy-service.yml
      dest: /home/vagrant/valaxy-service.yml

  - name: create a service
    command: kubectl delete -f valaxy-service.yml
    ignore_errors: yes

  - name: create a service
    command: kubectl apply -f valaxy-service.yml
